### ISSUE TITLE
How Connect To socket

### ISSUE THREAD

**Issue by MrAhmedElkady** [nedois/adonis-chat-demo#1]
Is there any code for connecting from the frontend using a Bearer Token? I found your code, but I can't connect because I can't find the correct connection method. I used this, but it didn't work.

```
import { Head } from "@inertiajs/react";
import io from "socket.io-client";

export default function Home(props: { version: number }) {
  const socket = io("http://localhost:3333/", {
    auth: {
      Authorization:
        "Bearer oat_NA.enFZQm8xaWpDN2V1M3BlZ2hiRnpGTkVvaTlLMmhIZ3dNem8tLXlHejM0OTA5NjcxOTc",
    },
  });

  return (
    <>
      <Head title="Homepage" />

      <div className="container">
        <div className="title">AdonisJS {props.version} x Inertia x React</div>

        <span>
          Learn more about AdonisJS and Inertia.js by visiting the{" "}
          <a href="https://docs.adonisjs.com/guides/inertia">
            AdonisJS documentation
          </a>
          .
        </span>
      </div>
    </>
  );
}
```

**Comment by nedois** [comment]
In this repo, the socket auth guard uses the [AccessTokenGuard](https://docs.adonisjs.com/guides/authentication/access-tokens-guard), you need to pass the ``Authorization`` token in the header of the handshake request:

```ts
const socket = io("http://localhost:3333/", {
    extraHeaders: {
      authorization:  "Bearer <token>",
    },
  });
```

**Comment by MrAhmedElkady** [comment]
This is great, it worked!
But can you provide some explanation for that repo? I need to explore it a lot.

Can you also explain some steps like:
`
emitter.emit('user:connected', { user, socket })
`
and
`
emitter.emit('user:disconnected', { user, socket })
`
What are they and how do they work? Or add a bit of explanation to your repository, which seems to be unique so far.

Adonis suffers from a lack of explanatory resources.
